export const allProducts = [
  {
    id: 1,
    name: "PixelForge",
    slug: "pixelforge",
    tagline: "Create stunning graphics directly in your browser",
    description:
      "PixelForge is a lightweight browser-based design tool that lets creators build banners, social media posts, and UI assets quickly without installing heavy software.",
    websiteUrl: "https://pixelforge.app",
    tags: ["Design", "Creator Tools"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "designhub@example.com",
    voteCount: 215,
  },
  {
    id: 2,
    name: "DevTrack",
    slug: "devtrack",
    tagline: "Track your coding progress every day",
    description:
      "DevTrack helps developers track coding hours, commits, and learning progress with detailed analytics and weekly insights.",
    websiteUrl: "https://devtrack.app",
    tags: ["Developer Tools", "Productivity"],
    createdAt: new Date("2024-02-02"),
    approvedAt: new Date("2024-02-03"),
    status: "approved" as const,
    submittedBy: "rahul.dev@example.com",
    voteCount: 142,
  },
  {
    id: 3,
    name: "ClipBoardy",
    slug: "clipboardy",
    tagline: "Smart clipboard manager for power users",
    description:
      "Save, search, and organize everything you copy with advanced clipboard history and quick search capabilities.",
    websiteUrl: "https://clipboardy.app",
    tags: ["Productivity", "Utilities"],
    createdAt: new Date("2024-02-05"),
    approvedAt: new Date("2024-02-06"),
    status: "approved" as const,
    submittedBy: "tools@example.com",
    voteCount: 93,
  },
  {
    id: 4,
    name: "LaunchBoost",
    slug: "launchboost",
    tagline: "Marketing toolkit for product launches",
    description:
      "LaunchBoost provides templates, analytics, and automation tools to help startups launch products successfully.",
    websiteUrl: "https://launchboost.io",
    tags: ["Marketing", "Startup"],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "startupfounder@example.com",
    voteCount: 521,
  },
  {
    id: 5,
    name: "GlobalPayKit",
    slug: "globalpaykit",
    tagline: "Accept payments worldwide effortlessly",
    description:
      "GlobalPayKit enables businesses to accept payments in multiple currencies with smart tax calculation and localization.",
    websiteUrl: "https://globalpaykit.com",
    tags: ["Fintech", "Payments", "SaaS"],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "payments@example.com",
    voteCount: 634,
  },
  {
    id: 6,
    name: "ChartCraft",
    slug: "chartcraft",
    tagline: "Build interactive charts in seconds",
    description:
      "ChartCraft helps analysts and developers convert raw data into interactive dashboards and reports with minimal effort.",
    websiteUrl: "https://chartcraft.app",
    tags: ["Analytics", "Data"],
    createdAt: new Date("2024-02-10"),
    approvedAt: new Date("2024-02-11"),
    status: "approved" as const,
    submittedBy: "analytics@example.com",
    voteCount: 276,
  },
  {
    id: 7,
    name: "MailPilot",
    slug: "mailpilot",
    tagline: "AI-powered email campaign automation",
    description:
      "MailPilot helps marketers create AI-optimized email campaigns with automated segmentation and performance tracking.",
    websiteUrl: "https://mailpilot.app",
    tags: ["Marketing", "Email", "Automation"],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "marketing@example.com",
    voteCount: 381,
  },
  {
    id: 8,
    name: "ServerPulse",
    slug: "serverpulse",
    tagline: "Real-time server monitoring platform",
    description:
      "ServerPulse monitors uptime, CPU usage, memory, and traffic across servers with instant alerts and detailed logs.",
    websiteUrl: "https://serverpulse.io",
    tags: ["Infrastructure", "DevOps"],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "approved" as const,
    submittedBy: "devops@example.com",
    voteCount: 458,
  },
  {
    id: 9,
    name: "Startup Finance 101",
    slug: "startup-finance-101",
    tagline: "Financial basics every founder must know",
    description:
      "A beginner-friendly course covering startup finance, fundraising strategies, budgeting, and financial planning.",
    websiteUrl: "https://startupfinance101.com",
    tags: ["Startup", "Finance", "Course"],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: "pending" as const,
    submittedBy: "foundercoach@example.com",
    voteCount: 198,
  },
];